// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_BBYRZo956gpSCoucDLdrJ7CNWp2mOI',
    appId: '1:927644121483:web:c59bc21d2caf39e422578e',
    messagingSenderId: '927644121483',
    projectId: 'cheider',
    authDomain: 'cheider.firebaseapp.com',
    storageBucket: 'cheider.appspot.com',
    measurementId: 'G-H4PBH0LN95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsoDEogU7CMK6raVfelGoPhJMkK8qlBjQ',
    appId: '1:927644121483:android:63d64f786871472822578e',
    messagingSenderId: '927644121483',
    projectId: 'cheider',
    storageBucket: 'cheider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeh_3W_CrU_M9IcNQBxfRSXlbDIcJPtLw',
    appId: '1:927644121483:ios:f7eb05ebb66ac13c22578e',
    messagingSenderId: '927644121483',
    projectId: 'cheider',
    storageBucket: 'cheider.appspot.com',
    iosClientId: '927644121483-379to3gbpb6b2iss8b8dkjteruvecf1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChessliderBeta0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeh_3W_CrU_M9IcNQBxfRSXlbDIcJPtLw',
    appId: '1:927644121483:ios:f7eb05ebb66ac13c22578e',
    messagingSenderId: '927644121483',
    projectId: 'cheider',
    storageBucket: 'cheider.appspot.com',
    iosClientId: '927644121483-379to3gbpb6b2iss8b8dkjteruvecf1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChessliderBeta0',
  );
}
